name: Pull Request

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Lint/Staticcheck get
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        install-go: false
        working-directory: get
    
    - name: Lint/Staticcheck ingest
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        install-go: false
        working-directory: ingest

    - name: Build scraper
      run: go build -v ./...
      working-directory: scraper
      
    - name: Test scraper
      run: go test -v ./...
      working-directory: scraper
   
    - name: Build proxy
      run: go build -v ./...
      working-directory: proxy
      
