name: Pull Request

on:
  pull_request:
    branches: '*'

jobs:
  testAndLint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Lint/Staticcheck scraper
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        install-go: false
        working-directory: scraper
    
    - name: Lint/Staticcheck proxy
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1"
        install-go: false
        working-directory: proxy

    - name: Build scraper
      run: go build -v ./...
      working-directory: scraper
      
    - name: Test scraper
      run: go test -v ./...
      working-directory: scraper
   
    - name: Build proxy
      run: go build -v ./...
      working-directory: proxy
    
    - name: Build jobNotifier
      run: go build -v ./...
      working-directory: jobNotifier
    
    - name: Test jobNotifier
      run: go test -v ./...
      working-directory: jobNotifier

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: v20.12.2
    
    - name: Install local dependencies
      run: npm install
      working-directory: local
    
    - name: build local typescript
      run: npx tsc
      working-directory: local
    
    - name: test local
      run: npm test
      working-directory: local